#!/bin/bash
fullname () {
  local myDIR=`dirname "$1"`
  local prev=`pwd`
  cd "$myDIR" >/dev/null
  realDIR=`pwd`
  cd "$prev" > /dev/null
  local basefile=`basename "$1"`
  echo "$realDIR/$basefile"
}

SCRIPT_NAME=`fullname $0`
FGLSETENVDIR=`dirname $SCRIPT_NAME` 
pushd $FGLSETENVDIR >/dev/null
#we recompile everything always: hence avoid version clashes
fglcomp -M fglsetenvGDC
if [ $? -ne 0 ]; then
  echo "Can't compile fglsetenvGDC"
  exit 1
fi
fglform -M fglsetenvGDC
if [ $? -ne 0 ]; then
  echo "Can't form compile fglsetenvGDC"
  exit 1
fi
export FGLSETENVDIR
export DBPATH=$FGLSETENVDIR
popd > /dev/null
exec fglrun $FGLSETENVDIR/fglsetenvGDC.42m "$@" 
